version: '2'
services:
    php-apache-dev:
        image: 'webdevops/php-apache-dev:8.3-alpine'
        links:
            - 'mysql:mysql'
        volumes:
            - './:/app'
        ports:
            - '80:80'
        depends_on:
            - mysql
        environment:
            - PHP_DISPLAY_ERRORS=1
            - extension
            - WEB_DOCUMENT_ROOT=/app/public
            - XDEBUG_MODE=debug
            - XDEBUG_DISCOVER_CLIENT_HOST=1
            - XDEBUG_START_WITH_REQUEST=trigger
            - XDEBUG_IDE_KEY=PHPSTORM
    mysql:
        image: 'mysql:8.3.0'
        environment:
            MYSQL_ROOT_PASSWORD: 'toor'
            MYSQL_DATABASE: 'test'
        volumes:
            - './.docker/mysql:/var/lib/mysql'
        ports:
            - '3306:3306'

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
        environment: [ 'ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false' ]
        ports:
            - "9200:9200"

    logstash:
        image: docker.elastic.co/logstash/logstash:8.4.2
        ports:
            - "5044:5044"
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        depends_on:
            - elasticsearch

    kibana:
        image: docker.elastic.co/kibana/kibana:8.4.2
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
